### ISSUE TITLE
Meaning of "Record entered in Inquire" and "Record last changed in Inquire"

### ISSUE THREAD

**Issue by mit2nil** [american-art/SAAM#4] opened 2017-01-04 20:12 UTC
Hi,

In file, WebConDates.csv, column "DateDescription", there are four different values. Two of them are birth and death date and the other are "Record entered in Inquire" and "Record last changed in Inquire".

How should we model these other two values?

Nilay

**Comment by rkbrasse** [comment] 2017-01-19 17:18
The inquire dates can be ignored.  That was a reference to an old data storage system.

**Comment by rkbrasse** [comment] 2017-03-03 12:51
Can we close this issue?  Just curious if we can do that with GH issues.

**Comment by workergnome** [comment] 2017-03-03 14:46
Absolutely.  If the issue is resolved to your satisfaction, please close.

**Comment by rkbrasse** [comment] 2017-03-03 15:04
I don't see any way to do so.  I assume those who opened it have to close it.

**Closed** 2017-03-03 16:01 UTC
